namespace Trellis.Core.Tests;

using System.Collections.Immutable;
using System.Globalization;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using SourceGenerator;

public class RequiredPartialClassGeneratorCollisionTests
{
    private const string CollisionDiagnosticId = "TRLS056";
    private static readonly MetadataReference[] _references = BuildReferences();

    [Fact]
    public void TryParse_Redeclared_UserMember_ReportsCollisionAndSkipsGeneratedMember()
    {
        const string source = """
            using System;
            using Trellis;

            namespace Demo;

            public sealed partial class RedeclaredText : RequiredString<RedeclaredText>
            {
                public static bool TryParse(string? s, IFormatProvider? provider, out RedeclaredText result)
                {
                    result = default!;
                    return false;
                }
            }
            """;

        var run = RunGenerator(source, TestContext.Current.CancellationToken);

        var diagnostic = run.RunResult.Diagnostics.Should().ContainSingle(d => d.Id == CollisionDiagnosticId).Which;
        diagnostic.Severity.Should().Be(DiagnosticSeverity.Error);
        diagnostic.GetMessage(CultureInfo.InvariantCulture).Should().Be("Member 'TryParse' is generated by Trellis for 'RedeclaredText' (a 'RequiredString' derivation). Remove the redundant declaration, or change the base class if you need custom semantics.");
        CompilerDuplicateDiagnostics(run).Should().BeEmpty();
        GeneratedSource(run).Should().NotContain("public static bool TryParse(");
    }

    [Fact]
    public void NewUniqueV7_Redeclared_UserMember_ReportsCollisionAndSkipsGeneratedMember()
    {
        const string source = """
            using Trellis;

            namespace Demo;

            public sealed partial class RedeclaredId : RequiredGuid<RedeclaredId>
            {
                public static RedeclaredId NewUniqueV7() => default!;
            }
            """;

        var run = RunGenerator(source, TestContext.Current.CancellationToken);

        var diagnostic = run.RunResult.Diagnostics.Should().ContainSingle(d => d.Id == CollisionDiagnosticId).Which;
        diagnostic.Severity.Should().Be(DiagnosticSeverity.Error);
        diagnostic.GetMessage(CultureInfo.InvariantCulture).Should().Be("Member 'NewUniqueV7' is generated by Trellis for 'RedeclaredId' (a 'RequiredGuid' derivation). Remove the redundant declaration, or change the base class if you need custom semantics.");
        CompilerDuplicateDiagnostics(run).Should().BeEmpty();
        var generated = GeneratedSource(run);
        generated.Should().NotContain("public static RedeclaredId NewUniqueV7() =>");
        generated.Should().Contain("public static RedeclaredId NewUniqueV7(TimeProvider timeProvider)");
    }

    [Fact]
    public void Generate_UnrelatedMethod_NoCollisionDiagnostic()
    {
        const string source = """
            using Trellis;

            namespace Demo;

            public sealed partial class CleanTextWithHelper : RequiredString<CleanTextWithHelper>
            {
                public static string Describe() => "ok";
            }
            """;

        var run = RunGenerator(source, TestContext.Current.CancellationToken);

        run.RunResult.Diagnostics.Should().NotContain(d => d.Id == CollisionDiagnosticId);
        CompilationDiagnostics(run).Where(d => d.Severity == DiagnosticSeverity.Error).Should().BeEmpty();
        GeneratedSource(run).Should().Contain("public static bool TryParse(");
    }

    [Fact]
    public void Generate_GenericMethodOverload_DoesNotCollideWithNonGenericGenerated()
    {
        // Round-4 pre-PR review caught this false positive: a user-declared generic Create<T>(...)
        // is a distinct overload from the generator's non-generic Create(...) and must not trigger
        // TRLS056. The signature-matching now uses MetadataName so generic arity differentiates.
        const string source = """
            using Trellis;

            namespace Demo;

            public sealed partial class GenericOverloadId : RequiredGuid<GenericOverloadId>
            {
                public static GenericOverloadId Create<TSource>(TSource value) => default!;
            }
            """;

        var run = RunGenerator(source, TestContext.Current.CancellationToken);

        run.RunResult.Diagnostics.Should().NotContain(d => d.Id == CollisionDiagnosticId);
        GeneratedSource(run).Should().Contain("public static GenericOverloadId Create(");
    }

    [Fact]
    public void Generate_UnrelatedExplicitConversion_DoesNotCollideWithGeneratedConversion()
    {
        // Round-4 pre-PR review caught this false positive: a user-declared
        // `operator string(MyId)` (converting the value object TO a string) is distinct from the
        // generator-emitted `operator MyId(Guid)` (converting Guid TO the value object). The
        // signature-matching now uses source+target types so unrelated conversions are not
        // treated as colliding.
        const string source = """
            using Trellis;

            namespace Demo;

            public sealed partial class UnrelatedConversionId : RequiredGuid<UnrelatedConversionId>
            {
                public static explicit operator string(UnrelatedConversionId id) => id.Value.ToString();
            }
            """;

        var run = RunGenerator(source, TestContext.Current.CancellationToken);

        run.RunResult.Diagnostics.Should().NotContain(d => d.Id == CollisionDiagnosticId);
        var generated = GeneratedSource(run);
        generated.Should().Contain("public static explicit operator UnrelatedConversionId(Guid");
    }

    [Fact]
    public void Generate_RedeclaredExplicitConversion_SameSourceAndTarget_StillReportsCollision()
    {
        // Regression: the source+target signature must still detect a real collision when the
        // user redeclares the SAME explicit conversion that the generator would emit.
        const string source = """
            using System;
            using Trellis;

            namespace Demo;

            public sealed partial class RedeclaredConversionId : RequiredGuid<RedeclaredConversionId>
            {
                public static explicit operator RedeclaredConversionId(Guid value) => default!;
            }
            """;

        var run = RunGenerator(source, TestContext.Current.CancellationToken);

        var diagnostic = run.RunResult.Diagnostics.Should().ContainSingle(d => d.Id == CollisionDiagnosticId).Which;
        diagnostic.Severity.Should().Be(DiagnosticSeverity.Error);
        CompilerDuplicateDiagnostics(run).Should().BeEmpty();
    }

    [Fact]
    public void Generate_CleanPartial_NoCollisionDiagnosticAndEmitsGeneratedMembers()
    {
        const string source = """
            using Trellis;

            namespace Demo;

            public sealed partial class CleanId : RequiredGuid<CleanId>
            {
            }
            """;

        var run = RunGenerator(source, TestContext.Current.CancellationToken);

        run.RunResult.Diagnostics.Should().NotContain(d => d.Id == CollisionDiagnosticId);
        CompilationDiagnostics(run).Where(d => d.Severity == DiagnosticSeverity.Error).Should().BeEmpty();
        var generated = GeneratedSource(run);
        generated.Should().Contain("public static bool TryParse(");
        generated.Should().Contain("public static CleanId NewUniqueV7() =>");
    }

    private static GeneratorRun RunGenerator(string source, CancellationToken cancellationToken)
    {
        var parseOptions = CSharpParseOptions.Default.WithLanguageVersion(LanguageVersion.Latest);
        var syntaxTree = CSharpSyntaxTree.ParseText(source, parseOptions, path: "UserCode.cs", encoding: Encoding.UTF8, cancellationToken: cancellationToken);
        var compilation = CSharpCompilation.Create(
            "RequiredPartialClassGeneratorCollisionTests",
            [syntaxTree],
            _references,
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary, nullableContextOptions: NullableContextOptions.Enable));

        GeneratorDriver driver = CSharpGeneratorDriver.Create(
            generators: ImmutableArray.Create<ISourceGenerator>(new RequiredPartialClassGenerator().AsSourceGenerator()),
            parseOptions: parseOptions);
        driver = driver.RunGeneratorsAndUpdateCompilation(compilation, out var outputCompilation, out _, cancellationToken);

        return new GeneratorRun(outputCompilation, driver.GetRunResult());
    }

    private static ImmutableArray<Diagnostic> CompilationDiagnostics(GeneratorRun run) =>
        run.Compilation.GetDiagnostics(TestContext.Current.CancellationToken);

    private static IEnumerable<Diagnostic> CompilerDuplicateDiagnostics(GeneratorRun run) =>
        CompilationDiagnostics(run).Where(d => d.Id is "CS0111" or "CS0102");

    private static string GeneratedSource(GeneratorRun run) =>
        run.RunResult.GeneratedTrees
            .Should().ContainSingle(tree => tree.FilePath.EndsWith(".g.cs", StringComparison.Ordinal))
            .Which.GetText(TestContext.Current.CancellationToken).ToString();

    private static MetadataReference[] BuildReferences()
    {
        var references = new Dictionary<string, MetadataReference>(StringComparer.OrdinalIgnoreCase);
        var trustedPlatformAssemblies = (string?)AppContext.GetData("TRUSTED_PLATFORM_ASSEMBLIES") ?? string.Empty;
        foreach (var referencePath in trustedPlatformAssemblies.Split(Path.PathSeparator, StringSplitOptions.RemoveEmptyEntries))
            references[referencePath] = MetadataReference.CreateFromFile(referencePath);

        references[typeof(Result).Assembly.Location] = MetadataReference.CreateFromFile(typeof(Result).Assembly.Location);

        return references.Values.ToArray();
    }

    private sealed record GeneratorRun(Compilation Compilation, GeneratorDriverRunResult RunResult);
}