<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <RootNamespace>ActorHandlers.ScanPersistence</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ActorHandlers.ScanApplication\ActorHandlers.ScanApplication.csproj" />
  </ItemGroup>
</Project>
