<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <Using Include="Trellis.EntityFrameworkCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\src\Trellis.EntityFrameworkCore.Outbox.csproj" />
    <ProjectReference Include="..\..\Trellis.Core\src\Trellis.Core.csproj" />
    <ProjectReference Include="..\..\Trellis.Mediator\src\Trellis.Mediator.csproj" />
    <ProjectReference Include="..\..\Trellis.Testing\src\Trellis.Testing.csproj" />
    <ProjectReference Include="..\..\Trellis.Core\generator\Trellis.Core.Generator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
  </ItemGroup>

</Project>
