<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <Using Include="Trellis.Authorization" />
    <Using Include="Trellis.Yarp" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Trellis.Testing\src\Trellis.Testing.csproj" />
    <ProjectReference Include="..\src\Trellis.Yarp.csproj" />
  </ItemGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Moq" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" />
  </ItemGroup>
</Project>
