<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Convert fluent validation errors to Trellis Validation errors.</Description>
    <PackageTags>trellis;validation;fluentvalidation;railway-oriented;result;error-handling;ddd</PackageTags>
    <IsAotCompatible>true</IsAotCompatible>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <TrellisApiRefName>fluentvalidation</TrellisApiRefName>
  </PropertyGroup>
  <ItemGroup>
  </ItemGroup>
	<ItemGroup>
		<PackageReference Include="FluentValidation" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\Trellis.Core\src\Trellis.Core.csproj" />
	</ItemGroup>
</Project>
