using ConditionalRequestExample.Data;
using ConditionalRequestExample.Domain;
using Trellis;
using Trellis.Asp;
using Trellis.EntityFrameworkCore;
using Trellis.Primitives;

namespace ConditionalRequestExample.Api;

public record CreateProductRequest(ProductName Name, MonetaryAmount Price);
public record UpdateProductRequest(MonetaryAmount Price);

/// <summary>
/// Wire response for a product. Uses VO wire types (A1b) so the
/// JSON shape matches the domain shape and clients see the same
/// validation contract as creation requests.
/// </summary>
public record ProductResponse(ProductId Id, ProductName Name, MonetaryAmount Price, string ETag)
{
    public static ProductResponse From(Product product) =>
        new(product.Id, product.Name, product.Price, product.ETag);
}

/// <summary>
/// Demonstrates RFC 9110 with OPTIONAL If-Match — updates proceed without the header.
/// Uses RepresentationMetadata for response headers and ConditionalRequestEvaluator for precondition checks.
/// </summary>
public static class OptionalETagRoutes
{
    public static void MapOptionalETagRoutes(this WebApplication app)
    {
        var group = app.MapGroup("/optional/products");

        // GET — returns ETag + Last-Modified headers; supports If-None-Match -> 304 Not Modified
        // Route param is bound directly as a ProductId (IParsable generated by Trellis).
        group.MapGet("/{id:guid}", (ProductId id, ProductDbContext db) =>
            db.Products
                .FirstOrDefaultResultAsync(p => p.Id == id, new Error.NotFound(new ResourceRef("Product", id.ToString(System.Globalization.CultureInfo.InvariantCulture))) { Detail = "Product not found." })
                .ToHttpResponseAsync(
                    ProductResponse.From,
                    opts => opts.WithETag(p => p.ETag).EvaluatePreconditions()));

        // POST — creates product, returns 201 Created + ETag
        group.MapPost("/", async (CreateProductRequest request, ProductDbContext db) =>
            await Product.TryCreate(request.Name, request.Price)
                .Tap(product => db.Products.Add(product))
                .CheckAsync(_ => db.SaveChangesResultUnitAsync())
                .ToHttpResponseAsync(
                    ProductResponse.From,
                    opts => opts.Created(p => $"/optional/products/{p.Id}").WithETag(p => p.ETag)))
            .WithScalarValueValidation();

        // PUT — If-Match is OPTIONAL. Without it, update proceeds unconditionally.
        // Uses typed EntityTagValue[] via ParseIfMatch.
        group.MapPut("/{id:guid}", (ProductId id, UpdateProductRequest request, ProductDbContext db, HttpContext httpContext) =>
            db.Products
                .FirstOrDefaultResultAsync(p => p.Id == id, new Error.NotFound(new ResourceRef("Product", id.ToString(System.Globalization.CultureInfo.InvariantCulture))) { Detail = "Product not found." })
                .OptionalETagAsync(ETagHelper.ParseIfMatch(httpContext.Request))
                .BindAsync(p => p.UpdatePrice(request.Price))
                .CheckAsync(_ => db.SaveChangesResultUnitAsync())
                .MapAsync(p => (WriteOutcome<Product>)new WriteOutcome<Product>.Updated(p, RepresentationMetadata.WithStrongETag(p.ETag)))
                .ToHttpResponseAsync(
                    ProductResponse.From,
                    opts => opts.HonorPrefer()))
            .WithScalarValueValidation();
    }
}

/// <summary>
/// Demonstrates RFC 9110 with REQUIRED If-Match — updates without the header get 428.
/// </summary>
public static class RequiredETagRoutes
{
    public static void MapRequiredETagRoutes(this WebApplication app)
    {
        var group = app.MapGroup("/required/products");

        // GET — returns ETag header; supports If-None-Match -> 304 Not Modified
        group.MapGet("/{id:guid}", (ProductId id, ProductDbContext db) =>
            db.Products
                .FirstOrDefaultResultAsync(p => p.Id == id, new Error.NotFound(new ResourceRef("Product", id.ToString(System.Globalization.CultureInfo.InvariantCulture))) { Detail = "Product not found." })
                .ToHttpResponseAsync(
                    ProductResponse.From,
                    opts => opts.WithETag(p => p.ETag).EvaluatePreconditions()));

        // POST — creates product, returns 201 Created + ETag
        group.MapPost("/", async (CreateProductRequest request, ProductDbContext db) =>
            await Product.TryCreate(request.Name, request.Price)
                .Tap(product => db.Products.Add(product))
                .CheckAsync(_ => db.SaveChangesResultUnitAsync())
                .ToHttpResponseAsync(
                    ProductResponse.From,
                    opts => opts.Created(p => $"/required/products/{p.Id}").WithETag(p => p.ETag)))
            .WithScalarValueValidation();

        // PUT — If-Match is REQUIRED. Without it -> 428 Precondition Required.
        // Uses typed EntityTagValue[] via ParseIfMatch.
        group.MapPut("/{id:guid}", (ProductId id, UpdateProductRequest request, ProductDbContext db, HttpContext httpContext) =>
            db.Products
                .FirstOrDefaultResultAsync(p => p.Id == id, new Error.NotFound(new ResourceRef("Product", id.ToString(System.Globalization.CultureInfo.InvariantCulture))) { Detail = "Product not found." })
                .RequireETagAsync(ETagHelper.ParseIfMatch(httpContext.Request))
                .BindAsync(p => Task.FromResult(p.UpdatePrice(request.Price)))
                .CheckAsync(_ => db.SaveChangesResultUnitAsync())
                .MapAsync(p => (WriteOutcome<Product>)new WriteOutcome<Product>.Updated(p, RepresentationMetadata.WithStrongETag(p.ETag)))
                .ToHttpResponseAsync(
                    ProductResponse.From,
                    opts => opts.HonorPrefer()))
            .WithScalarValueValidation();
    }
}