namespace Trellis.AspSourceGenerator;

using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

/// <summary>
/// Emits compile-time-closed path-tracking converter registrations so index-precise validation field
/// paths (<c>/members/0/email</c>) work under Native AOT, at parity with the reflection pipeline.
/// </summary>
/// <remarks>
/// <para>
/// The reflection pipeline builds <c>PathTrackingObjectConverter&lt;T&gt;</c> and
/// <c>PathTrackingCollectionConverter&lt;TCollection, TElement&gt;</c> with
/// <c>Type.MakeGenericType</c> at runtime, which Native AOT forbids. This generator performs the
/// equivalent DTO graph walk at compile time — starting from every type named by a
/// <c>[JsonSerializable]</c> attribute — and emits a <c>[ModuleInitializer]</c> that hands the closed
/// instantiations to <c>ScalarValuePathTracking</c>.
/// </para>
/// <para>
/// The walk mirrors the runtime rules in <c>Trellis.Asp.ServiceCollectionExtensions</c> exactly. Any
/// divergence would make AOT and reflection disagree about which properties are wrapped, which is the
/// precise class of bug this feature exists to remove, so the two rule sets are kept structurally
/// identical: same collection shapes, same user-object definition, same transitive-containment test.
/// </para>
/// </remarks>
[Generator]
public sealed class PathTrackingRegistryGenerator : IIncrementalGenerator
{
    private const string JsonSerializableAttribute = "System.Text.Json.Serialization.JsonSerializableAttribute";
    private const string ScalarValueInterface = "Trellis.IScalarValue`2";
    private const string MaybeType = "Trellis.Maybe`1";

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var roots = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                JsonSerializableAttribute,
                predicate: static (_, _) => true,
                transform: static (ctx, _) => GetSerializableRoots(ctx))
            .SelectMany(static (types, _) => types);

        var combined = context.CompilationProvider.Combine(roots.Collect());

        context.RegisterSourceOutput(combined, static (spc, source) => Execute(source.Left, source.Right, spc));
    }

    private static ImmutableArray<INamedTypeSymbol> GetSerializableRoots(GeneratorAttributeSyntaxContext context)
    {
        var builder = ImmutableArray.CreateBuilder<INamedTypeSymbol>();

        foreach (var attribute in context.Attributes)
        {
            if (attribute.ConstructorArguments.Length == 0)
                continue;

            if (attribute.ConstructorArguments[0].Value is INamedTypeSymbol type)
                builder.Add(type);
        }

        return builder.ToImmutable();
    }

    private static void Execute(Compilation compilation, ImmutableArray<INamedTypeSymbol> roots, SourceProductionContext context)
    {
        if (roots.IsDefaultOrEmpty)
            return;

        var walker = new GraphWalker(compilation);
        foreach (var root in roots)
            walker.Walk(root);

        if (walker.ObjectRegistrations.Count == 0 && walker.CollectionRegistrations.Count == 0)
            return;

        context.AddSource("TrellisScalarValuePathTracking.g.cs", Emit(walker));
    }

    private static string Emit(GraphWalker walker)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace Trellis.Asp.Generated;");
        sb.AppendLine();
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using Trellis.Asp.Validation;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Registers compile-time-closed path-tracking converters so scalar value-object validation");
        sb.AppendLine("/// failures report index-precise field paths under Native AOT, where the runtime cannot");
        sb.AppendLine("/// construct the closed generics itself.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("internal static class TrellisScalarValuePathTracking");
        sb.AppendLine("{");
        sb.AppendLine("    [ModuleInitializer]");
        sb.AppendLine("    internal static void Register()");
        sb.AppendLine("    {");

        foreach (var type in walker.ObjectRegistrations)
            sb.AppendLine($"        ScalarValuePathTracking.RegisterObject<{type}>();");

        foreach (var pair in walker.CollectionRegistrations)
            sb.AppendLine($"        ScalarValuePathTracking.RegisterCollection<{pair.Collection}, {pair.Element}>();");

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// Compile-time mirror of the runtime DTO graph walk.
    /// </summary>
    private sealed class GraphWalker
    {
        private static readonly SymbolDisplayFormat FullyQualified = SymbolDisplayFormat.FullyQualifiedFormat;

        private readonly Compilation _compilation;
        private readonly INamedTypeSymbol? _scalarValueInterface;
        private readonly INamedTypeSymbol? _maybeType;
        private readonly INamedTypeSymbol? _listType;
        private readonly HashSet<ITypeSymbol> _visited = new(SymbolEqualityComparer.Default);

        public GraphWalker(Compilation compilation)
        {
            _compilation = compilation;
            _scalarValueInterface = compilation.GetTypeByMetadataName(ScalarValueInterface);
            _maybeType = compilation.GetTypeByMetadataName(MaybeType);
            _listType = compilation.GetTypeByMetadataName("System.Collections.Generic.List`1");
        }

        public SortedSet<string> ObjectRegistrations { get; } = new(System.StringComparer.Ordinal);

        public SortedSet<CollectionRegistration> CollectionRegistrations { get; } = new();

        public void Walk(ITypeSymbol type)
        {
            if (!_visited.Add(type))
                return;

            var element = GetEnumerableElementType(type);
            if (element is not null)
            {
                Walk(element);
                return;
            }

            if (!IsUserObjectType(type))
                return;

            foreach (var property in GetSerializableProperties(type))
            {
                var propertyType = property.Type;

                // A property that IS a scalar value object (or Maybe<scalar>) is handled by the scalar
                // converter path in the runtime modifier, which `continue`s before ever reaching the
                // container path. Wrapping it here would register a converter the reflection pipeline
                // never installs, so AOT and reflection would disagree.
                if (IsScalarValue(propertyType) || IsMaybeScalarValue(propertyType))
                    continue;

                if (!ContainsScalarValueTransitively(propertyType, new HashSet<ITypeSymbol>(SymbolEqualityComparer.Default)))
                    continue;

                var wrappableElement = GetWrappableCollectionElementType(propertyType);
                if (wrappableElement is not null)
                {
                    if (IsAccessible(propertyType) && IsAccessible(wrappableElement))
                    {
                        CollectionRegistrations.Add(new CollectionRegistration(
                            propertyType.ToDisplayString(FullyQualified),
                            wrappableElement.ToDisplayString(FullyQualified)));
                    }

                    Walk(wrappableElement);
                    continue;
                }

                if (!IsUserObjectType(propertyType))
                    continue;

                if (IsAccessible(propertyType))
                    ObjectRegistrations.Add(propertyType.ToDisplayString(FullyQualified));

                Walk(propertyType);
            }
        }

        // Mirrors Type.GetProperties(BindingFlags.Public | BindingFlags.Instance) in the runtime
        // modifier, which includes properties inherited from base types.
        private static IEnumerable<IPropertySymbol> GetSerializableProperties(ITypeSymbol type)
        {
            var seen = new HashSet<string>(StringComparer.Ordinal);

            for (var current = type; current is not null && current.SpecialType != SpecialType.System_Object; current = current.BaseType)
            {
                foreach (var property in current.GetMembers().OfType<IPropertySymbol>())
                {
                    if (property.IsStatic
                        || property.Parameters.Length != 0
                        || property.DeclaredAccessibility != Accessibility.Public)
                        continue;

                    if (seen.Add(property.Name))
                        yield return property;
                }
            }
        }

        private bool ContainsScalarValueTransitively(ITypeSymbol type, HashSet<ITypeSymbol> visited)
        {
            if (!visited.Add(type))
                return false;

            if (IsScalarValue(type) || IsMaybeScalarValue(type))
                return true;

            var element = GetEnumerableElementType(type);
            if (element is not null)
                return ContainsScalarValueTransitively(element, visited);

            if (!IsUserObjectType(type))
                return false;

            foreach (var property in GetSerializableProperties(type))
            {
                if (ContainsScalarValueTransitively(property.Type, visited))
                    return true;
            }

            return false;
        }

        private bool IsScalarValue(ITypeSymbol type) =>
            _scalarValueInterface is not null
            && type.AllInterfaces.Any(i => SymbolEqualityComparer.Default.Equals(i.OriginalDefinition, _scalarValueInterface));

        private bool IsMaybeScalarValue(ITypeSymbol type) =>
            _maybeType is not null
            && type is INamedTypeSymbol { TypeArguments.Length: 1 } named
            && SymbolEqualityComparer.Default.Equals(named.OriginalDefinition, _maybeType)
            && IsScalarValue(named.TypeArguments[0]);

        // Mirrors the runtime rule: an array element, or an element whose List<element> is assignable
        // back to the declared property type. Other collection shapes are left to STJ (leaf-only paths).
        private ITypeSymbol? GetWrappableCollectionElementType(ITypeSymbol type)
        {
            if (type is IArrayTypeSymbol array)
                return array.ElementType;

            var element = GetEnumerableElementType(type);
            if (element is null || _listType is null)
                return null;

            var listOfElement = _listType.Construct(element);
            return _compilation.ClassifyCommonConversion(listOfElement, type).IsImplicit ? element : null;
        }

        private static ITypeSymbol? GetEnumerableElementType(ITypeSymbol type)
        {
            if (type.SpecialType == SpecialType.System_String)
                return null;

            if (type is IArrayTypeSymbol array)
                return array.ElementType;

            if (type is INamedTypeSymbol { TypeArguments.Length: 1 } named
                && named.OriginalDefinition.SpecialType == SpecialType.System_Collections_Generic_IEnumerable_T)
                return named.TypeArguments[0];

            foreach (var iface in type.AllInterfaces)
            {
                if (iface.OriginalDefinition.SpecialType == SpecialType.System_Collections_Generic_IEnumerable_T)
                    return iface.TypeArguments[0];
            }

            return null;
        }

        private static bool IsUserObjectType(ITypeSymbol type)
        {
            if (type.TypeKind != TypeKind.Class || type is IArrayTypeSymbol)
                return false;

            if (type.SpecialType is SpecialType.System_String or SpecialType.System_Object)
                return false;

            var ns = type.ContainingNamespace;
            if (ns is null || ns.IsGlobalNamespace)
                return true;

            var root = ns;
            while (root.ContainingNamespace is { IsGlobalNamespace: false } parent)
                root = parent;

            return root.Name != "System";
        }

        // The generated registration lives in the consumer assembly, so every type it names must be
        // reachable from there. A private or protected nested DTO is skipped rather than emitted as
        // uncompilable code.
        private static bool IsAccessible(ITypeSymbol type)
        {
            if (type is IArrayTypeSymbol array)
                return IsAccessible(array.ElementType);

            for (ITypeSymbol? current = type; current is not null; current = current.ContainingType)
            {
                if (current.DeclaredAccessibility is not (Accessibility.Public or Accessibility.Internal or Accessibility.NotApplicable))
                    return false;
            }

            if (type is INamedTypeSymbol named)
            {
                foreach (var argument in named.TypeArguments)
                {
                    if (!IsAccessible(argument))
                        return false;
                }
            }

            return true;
        }
    }

    /// <summary>
    /// A <c>PathTrackingCollectionConverter&lt;TCollection, TElement&gt;</c> instantiation to register.
    /// </summary>
    private readonly struct CollectionRegistration : System.IComparable<CollectionRegistration>
    {
        public CollectionRegistration(string collection, string element)
        {
            Collection = collection;
            Element = element;
        }

        public string Collection { get; }

        public string Element { get; }

        public int CompareTo(CollectionRegistration other)
        {
            var byCollection = System.StringComparer.Ordinal.Compare(Collection, other.Collection);
            return byCollection != 0 ? byCollection : System.StringComparer.Ordinal.Compare(Element, other.Element);
        }
    }
}
