<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TrellisEnableApiReferenceLint>true</TrellisEnableApiReferenceLint>
    <IsPackable>false</IsPackable>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <EnablePackageValidation>false</EnablePackageValidation>
    <ProduceReferenceAssembly>false</ProduceReferenceAssembly>
    <EnableTrimAnalyzer>false</EnableTrimAnalyzer>
    <EnableAotAnalyzer>false</EnableAotAnalyzer>
  </PropertyGroup>
</Project>